from tau2.utils.utils import DATA_DIR

EV_CHARGING_SUPPORT_DATA_DIR = DATA_DIR / "tau2" / "domains" / "ev_charging_support"
EV_CHARGING_SUPPORT_DB_PATH = EV_CHARGING_SUPPORT_DATA_DIR / "db.json"
EV_CHARGING_SUPPORT_USER_DB_PATH = EV_CHARGING_SUPPORT_DATA_DIR / "user_db.json"
EV_CHARGING_SUPPORT_POLICY_PATH = EV_CHARGING_SUPPORT_DATA_DIR / "policy.md"
EV_CHARGING_SUPPORT_TASK_SET_PATH = EV_CHARGING_SUPPORT_DATA_DIR / "tasks.depgraph.json"

