"""Compile depgraph artifacts into verifiers-ready configurations.

This module is the verifiers equivalent of compiler.py + runtime_scaffold.py.
It takes a GraphContractSpec + TaskSpecsDoc and produces DepgraphTaskConfig
objects that can be used with DepgraphToolEnv.

The tau2 compiler produces Task JSON with initialization_actions, env_assertions,
and action expectations. This compiler produces DepgraphTaskConfig objects with
start_world dicts, goal predicates, and task prompts — everything the
DepgraphToolEnv needs to run an episode.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

from tau2.generators.depgraph.preflight import run_task_preflight, terminal_profile_map
from tau2.generators.depgraph.types import (
    GraphContractSpec,
    TaskIntent,
    TaskSpecsDoc,
    TerminalProfileSpec,
)
from tau2.generators.depgraph.verifiers_env import (
    DepgraphTaskConfig,
    compile_task_config,
)


@dataclass
class VerifiersCompileResult:
    """Result of compiling depgraph tasks for verifiers."""

    configs: list[DepgraphTaskConfig] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)

    @property
    def success(self) -> bool:
        return not self.errors


def compile_for_verifiers(
    contract: GraphContractSpec,
    task_doc: TaskSpecsDoc,
    *,
    task_prompt_factory: Callable[[TaskIntent, GraphContractSpec], str] | None = None,
    system_prompt: str = "",
    max_depth: int | None = None,
    terminal_profiles: list[TerminalProfileSpec] | None = None,
) -> VerifiersCompileResult:
    """Compile depgraph tasks into DepgraphTaskConfig objects for verifiers.

    This runs preflight checks on each task (same as the tau2 compiler) and
    then produces configs for the ones that pass. Unlike the tau2 compiler,
    it does NOT require RuntimeTaskSpec payloads — the task prompt is
    generated by ``task_prompt_factory`` or left empty for the caller to fill.

    Parameters
    ----------
    contract:
        The graph contract.
    task_doc:
        Task specs (from sampler output or hand-authored).
    task_prompt_factory:
        Optional function that generates a natural-language task prompt
        from a TaskIntent. If None, task_prompt is left empty.
    system_prompt:
        System prompt prepended to every task's agent context.
    max_depth:
        Max BFS depth for preflight. Defaults to max(20, max task depth).
    terminal_profiles:
        Terminal profiles for preflight validation. If None, preflight
        skips terminal-profile checks.
    """
    result = VerifiersCompileResult()

    effective_max_depth = max_depth
    if effective_max_depth is None:
        effective_max_depth = max(
            20,
            max((task.min_plan_length for task in task_doc.tasks), default=0),
        )

    profiles_by_id = (
        terminal_profile_map(terminal_profiles)
        if terminal_profiles
        else None
    )

    for task in task_doc.tasks:
        report = run_task_preflight(
            contract,
            task,
            max_depth=effective_max_depth,
            terminal_profiles=profiles_by_id,
            require_terminal_profile=profiles_by_id is not None,
            check_required_action_necessity=False,
        )
        if not report.passed:
            result.skipped.append(task.task_id)
            reason = "; ".join(report.issues) if report.issues else (
                f"SAT_full={report.sat_full.sat}"
            )
            result.errors.append(f"{task.task_id}: preflight failed - {reason}")
            continue

        task_prompt = ""
        if task_prompt_factory is not None:
            task_prompt = task_prompt_factory(task, contract)

        try:
            config = compile_task_config(
                contract,
                task,
                system_prompt=system_prompt,
                task_prompt=task_prompt,
            )
            result.configs.append(config)
        except ValueError as exc:
            result.skipped.append(task.task_id)
            result.errors.append(f"{task.task_id}: compile failed - {exc}")

    return result
