from tau2.utils.utils import DATA_DIR

ONLINE_SHOPPING_DATA_DIR = DATA_DIR / "tau2" / "domains" / "online_shopping"
ONLINE_SHOPPING_DB_PATH = ONLINE_SHOPPING_DATA_DIR / "db.json"
ONLINE_SHOPPING_USER_DB_PATH = ONLINE_SHOPPING_DATA_DIR / "user_db.json"
ONLINE_SHOPPING_POLICY_PATH = ONLINE_SHOPPING_DATA_DIR / "policy.md"
ONLINE_SHOPPING_TASK_SET_PATH = ONLINE_SHOPPING_DATA_DIR / "tasks.json"
