from tau2.utils.utils import DATA_DIR

TRAVEL_AGENCY_DATA_DIR = DATA_DIR / "tau2" / "domains" / "travel_agency"
TRAVEL_AGENCY_DB_PATH = TRAVEL_AGENCY_DATA_DIR / "db.json"
TRAVEL_AGENCY_USER_DB_PATH = TRAVEL_AGENCY_DATA_DIR / "user_db.json"
TRAVEL_AGENCY_POLICY_PATH = TRAVEL_AGENCY_DATA_DIR / "policy.md"
TRAVEL_AGENCY_TASK_SET_PATH = TRAVEL_AGENCY_DATA_DIR / "tasks.json"
