from tau2.utils.utils import DATA_DIR

CLOUD_INCIDENT_DATA_DIR = DATA_DIR / "tau2" / "domains" / "cloud_incident_response"
CLOUD_INCIDENT_DB_PATH = CLOUD_INCIDENT_DATA_DIR / "db.json"
CLOUD_INCIDENT_USER_DB_PATH = CLOUD_INCIDENT_DATA_DIR / "user_db.json"
CLOUD_INCIDENT_POLICY_PATH = CLOUD_INCIDENT_DATA_DIR / "policy.md"
CLOUD_INCIDENT_TASK_SET_PATH = CLOUD_INCIDENT_DATA_DIR / "tasks.depgraph.json"
