from tau2.utils.utils import DATA_DIR

FITNESS_GYM_DATA_DIR = DATA_DIR / "tau2" / "domains" / "fitness_gym"
FITNESS_GYM_DB_PATH = FITNESS_GYM_DATA_DIR / "db.json"
FITNESS_GYM_USER_DB_PATH = FITNESS_GYM_DATA_DIR / "user_db.json"
FITNESS_GYM_POLICY_PATH = FITNESS_GYM_DATA_DIR / "policy.md"
FITNESS_GYM_TASK_SET_PATH = FITNESS_GYM_DATA_DIR / "tasks.json"
